"""Paths to datasets."""


DATA_PATHS = {'mnist': './datasets/mnist.pckl',
              'small_mnist': './datasets/small_mnist.pckl',
              'halves_mnist': './datasets/halves_mnist.pckl',
              'halves_same_mnist': './datasets/halves_same_mnist.pckl',
              'stacked_mnist': './datasets/stacked_mnist.pckl',
              'stacked_same_mnist': './datasets/stacked_same_mnist.pckl',
              'cifar10': './datasets/cifar10.pckl',
              'halves_cifar10': './datasets/halves_cifar10.pckl',
              'halves_same_cifar10': './datasets/halves_same_cifar10.pckl',
              'stacked_cifar10': './datasets/stacked_cifar10.pckl',
              'stacked_same_cifar10': './datasets/stacked_same_cifar10.pckl',
              'cifar10_full': './datasets/cifar10_full.pckl',
              'line': './datasets/line.pckl',
              'fashion': './datasets/fashion.pckl',
              'halves_fashion': './datasets/halves_fashion.pckl',
              'halves_same_fashion': './datasets/halves_same_fashion.pckl',
              'stacked_fashion': './datasets/stacked_fashion.pckl',
              'stacked_same_fashion': './datasets/stacked_same_fashion.pckl',
              'random': './datasets/random.pckl',
              'line-mnist': './datasets/line-mnist.pckl',
              'line-cifar10': './datasets/line-cifar10.pckl',
              'mnist-fashion': './datasets/mnist-fashion.pckl',
              'mnist-cifar10': './datasets/mnist-cifar10.pckl',
              'fashion-cifar10': './datasets/fashion-cifar10.pckl',
              'line-mnist-separated': './datasets/line-mnist-separated.pckl',
              'line-cifar10-separated': './datasets/line-cifar10-separated.pckl',
              'mnist-cifar10-separated': './datasets/mnist-cifar10-separated.pckl',
              'mnist-fashion-separated': './datasets/mnist-fashion-separated.pckl',
              'fashion-cifar10-separated': './datasets/fashion-cifar10-separated.pckl',
              'poly': './datasets/poly.pckl'}
